projet_homepage:
    path:     /
    defaults: { _controller: ProjetBundle:Default:index }


connexion:
    path:     /connexion
    defaults: { _controller: ProjetBundle:Default:connexion }

creation_recette:
    path:     /creation
    defaults: { _controller: ProjetBundle:Recette:creation }

test:
    path:    /test
    defaults: { _controller: ProjetBundle:Default:test }
